### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [millennialsforchrist/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by justinrjoseph** [comment]
I pushed a few updates. I think I took care of what you pointed out.

**Comment by kenmazaika** [comment]
Looks solid!  :+1:
